name: presentation
description: Presentation layer.
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^2.0.0
  

flutter:
  generate: true

  assets:
    - ../../assets/icons/