name: domain
description: Domain layer.
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
